name: Github actions for CI

on:
  push:
    branches:
      - main

jobs:
  build-docker-image-deploy:
    runs-on: ubuntu-latest

    env:
      ENABLE_GHCR_PUSH: "true"
      ENABLE_RAILWAY_DEPLOY: "false"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Login to GHCR
        if: env.ENABLE_GHCR_PUSH == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ env.ENABLE_GHCR_PUSH == 'true' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            BLOGS_REPOSITORY=supabase

      - name: Install Railway CLI
        if: env.ENABLE_RAILWAY_DEPLOY == 'true'
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        if: env.ENABLE_RAILWAY_DEPLOY == 'true'
        run: railway up --ci --service "${{ secrets.RAILWAY_SERVICE_NAME }}"
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
